version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: tupi_digital_db
    environment:
      POSTGRES_USER: tupidigital
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: tupi_digital
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
